ydlidar_node:
  ros__parameters:
    port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 128000
    samp_rate: 5
    resolution_fixed: true
    singleChannel: false
    auto_reconnect: true
    reversion: true
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 16.0
    min_range: 0.01
    frequency: 10.0
